# Permalinks
permalink:      /:year-:month-:day/:title

# img_path
imgpath: glqdlt.github.io/_img

# Setup
title:          Glqdlt's Blog
paginate:       10
baseurl:        ""
url:            https://glqdlt.github.io/

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Il woong, Jhun
  url:          http://chester.how
  email:        dlfdnd0725@gmail.com

# Custom vars

version:        3.4.1
github:
  repo:         https://github.com/glqdlt/glqdlt.github.io

# Gems
gems:
  - jekyll-paginate


#disqus
disqus:       disqus_gSPuQXPFbO

#disqus option
---
layout: default
comments: true
# other options
---
