# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          코딩 넘모조아
paginate:       15
baseurl:        ""
url:            https://glqdlt.github.io/

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Iw Jhun
  url:          https://glqdlt.github.io/
  email:        dlfdnd0725@gmail.com

# Custom vars

version:        3.4.1
github:
  repo:         https://github.com/glqdlt/glqdlt.github.io

# Gems
gems:
  - jekyll-paginate


#disqus option
---
layout: default
comments: true
# other options
---
