@startuml

actor user as u
component "GUI CMS" as cms
component "배치 API 서버" as eas
database "큐 및 로그저장 Mysql" as db
node "엑셀 추출 배치" as en{
    component "엑셀 스프링 배치1"
    component "엑셀 스프링 배치2"
}
node "작업 처리 배치" as psn{
    component "작업 스프링 배치1"
    component "작업 스프링 배치2"
}

node "외부 인프라 서버" as eps

u --> cms : 1) 엑셀 업로드
cms -> eas : 2) 엑셀 업로드
eas -> db : 3) 작업 저장 (엑셀 저장)
en -> db : 4) 작업 폴링
en --> db : 5) 엑셀에서 명단 추출, 다음 작업 저장
psn -> db : 6) 작업 폴링
psn --> eps : 7) 작업 순차 처리

@enduml